# Generated by Django 5.2.14 on 2026-05-31 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='created_at',
        ),
    ]
